build scripts now monolithic

diff --git a/build_scripts/lorax_tool b/build_scripts/lorax_tool
--- a/build_scripts/lorax_tool
+++ b/build_scripts/lorax_tool
@@ -35,7 +35,7 @@ Commands:
           build - metacommand to build all configured binary packages.
          config - Set/print build-time configuration variables.
   configure_pkg - metacommand to configure the ${pkg} instance.
-       download - Downloads self and other scripts.
+ create_scripts - creates/updates my_build.sh and my_config.sh customization scripts.
            init - Set system-specific defaults for the build.
         install - Install one or all binary packages.
        link_env - Link the ${pkg}_env file to bin_dir for convenience.
@@ -45,6 +45,7 @@ Commands:
            pypi - Get latest pypi version.
           shell - Run a shell in installation environment.
         testify - Run tests.
+         update - Updates this script.
         version - Get installed ${pkg} version.
 
 Variables (accessed by \"config\" command):
@@ -204,7 +205,7 @@ You should stop and edit my_build.sh if you wish to:
 You may run this command with a \"-y\" argument to skip this question.
 """
    if [ "$1" != "-y" ]; then
-      echo "$DOC"
+      echo "$BUILD_DOC"
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -215,7 +216,12 @@ You may run this command with a \"-y\" argument to skip this question.
    fi
    # Configure the build.
    init
-   source my_build.sh
+   if [ -e my_build.sh]; then
+      echo "Sourcing build specifics in my_build.sh."
+      source my_build.sh
+   else
+      echo "WARNING--my_build.sh not found, using defaults."
+   fi
    set_value all
    make_dirs
    # Build the binaries.
@@ -236,7 +242,8 @@ You may run this command with a \"-y\" argument to skip this question.
    link_env       # put lorax_env in PATH
    # Test to make sure it runs.
    echo "Testing lorax binary."
-   version > ${root_dir}/version
+   root="`get_value root_dir`"
+   version > ${root}/version
    echo "Installation was successful."
    echo "You should now proceed with configuring lorax via the command"
    echo "   lorax_tool configure_pkg"
@@ -258,13 +265,13 @@ Arguments:
       exit 1
     elif [ "$#" -eq 1 ]; then # get
       if [ "$1" == "all" ]; then
-        echo "Build configuration values for ${pkg}."
-        echo "These values are stored in ${confdir}."
-        echo -e "       key         \t       value"
-        echo -e "-------------------\t------------------"
+        echo "Build configuration values for ${pkg}." >&1
+        echo "These values are stored in ${confdir}." >&1
+        echo -e "       key         \t       value" >&1
+        echo -e "-------------------\t------------------" >&1
         for key in `ls ${confdir}`; do
           value=`get_value ${key}`
-        printf '%-20s\t%s\n' ${key} ${value}
+        printf '%-20s\t%s\n' ${key} ${value} >&1
       done
     elif [ -e ${confdir}/${1} ]; then
       echo `get_value $1`
@@ -293,7 +300,7 @@ You should stop and edit my_config.sh if you wish to:
 You may run this command with a \"-y\" argument to skip this question.
 """
    if [ "$1" != "-y" ]; then
-      echo "$CONFIGURE_DOC"
+      echo "$CONFIGURE_DOC" >&1
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -308,67 +315,114 @@ You may run this command with a \"-y\" argument to skip this question.
    log_dir="`get_value log_dir`"
    tmp_dir="`get_value tmp_dir`"
    if [ "$var_dir" != "${root}/var" ]; then
-      echo "Configuring non-default var directory ${var_dir}."
+      echo "Configuring non-default var directory ${var_dir}." >&1
       ${root}/bin/lorax_env lorax config var $var_dir
    fi
    if [ "$log_dir" != "${var_dir}/log" ]; then
-      echo "Configuring non-default log directory ${log_dir}."
+      echo "Configuring non-default log directory ${log_dir}." >&1
       ${root}/bin/lorax_env lorax config log $log_dir
    fi
    if [ "$tmp_dir" != "${var_dir}/tmp" ]; then
-      echo "Configuring non-default tmp directory ${tmp_dir}."
+      echo "Configuring non-default tmp directory ${tmp_dir}." >&1
       ${root}/bin/lorax_env lorax config tmp $tmp_dir
    fi
-   source my_config.sh
+   if [ -e my_config.sh]; then
+      echo "Sourcing configuration specifics in my_config.sh."
+      source my_config.sh
+   else
+      echo "WARNING--my_config.sh not found, using defaults."
+   fi
    # Save a copy of the configuration to a time-stamped file.
    config_filename="lorax_config-`date '+%Y-%m-%d-%H-%M'`.txt"
    ${root}/bin/lorax_env lorax config > ${root}/config/${config_filename}
    # Create the configured instance.
-   echo "Creating a configured instance at ${root}."
+   echo "Creating a configured instance at ${root}." >&1
    ${root}/bin/lorax_env lorax create_instance --force
    # Set the password for restricted parts of the site.
    passwd="`${root}/bin/lorax_env lorax config secret_key`"
-   echo "Setting the http password to \"${passwd}\";"
-   echo "please write it down, because you will need it to access some services."
+   echo "Setting the http password to \"${passwd}\";" >&1
+   echo "please write it down, because you will need it to access some services." >&1
    ${root}/bin/lorax_env lorax set_htpasswd --force
-   echo "To run the test suite, issue the command:"
-   echo "   ./${script_name} testify"
+   echo "To run the test suite, issue the command:" >&1
+   echo "   ./${script_name} testify" >&1
 }
-download() {
-DOWNLOAD_DOC="""Gets/updates build/configuration scripts for ${pkg}.
+create_scripts() {
+(
+cat << 'EOF'
+#
+# lorax_tool init configures the following default values, which you may
+# override by uncommenting here.  These default values are for a linux
+# build and may be different then the values created by lorax_tools init
+# command.
+#
+# Note that if you are building nginx, some of these configuration values
+# are compile-time-only settings which cannot be overridden.
+#
+#./lorax_tool config directory_version 0.94
+#./lorax_tool config root_dir ~/.lorax/`./lorax_tool config directory_version`
+#./lorax_tool config var_dir "`./lorax_tool config root_dir`/var"
+#./lorax_tool config tmp_dir "`./lorax_tool config var_dir`/tmp"
+#./lorax_tool config log_dir "`./lorax_tool config var_dir`/log"
+#
+# Version numbers of packages.  Setting these to "system" will cause them
+# not to be built.
+#
+#./lorax_tool config python 3.6.2
+#./lorax_tool config hmmer 3.1b2
+#./lorax_tool config raxml 8.2.11
+#./lorax_tool config redis 4.0.1
+#./lorax_tool config nginx 1.13.4
+#
+# The following defaults are platform-specific.  Linux defaults are shown.
+#
+#./lorax_tool config platform linux
+#./lorax_tool config bin_dir ~/bin  # dir in PATH where lorax_env is symlinked
+#./lorax_tool config make make
+#./lorax_tool config cc gcc
+#./lorax_tool config redis_cflags ""
+#
+# The following defaults are hardware-specific for the RAxML build.
+# If you have both hardware and compiler support, you may wish to substitute
+# "SSE3" with either "AVX" or "AVX2".  Note that clang on BSD uses the gcc
+# model, but mac has its own model.
+#
+#./lorax_tool config raxml_model .SSE3.PTHREADS.gcc
+#./lorax_tool config raxml_binsuffix -PTHREADS-SSE3
+#
+EOF
+) > build_example.sh.new
 
-Options:
-       -n Do not check for self-updates.
-"""
-   rawsite="https://raw.githubusercontent.com/LegumeFederation/${pkg}/master/build_scripts"
-   updates=0
-   if [ "$1" == "-n" ]; then
-      echo "Not checking for self-updates."
-   else
-      printf "Checking for self-update..."
-      curl -L -s -o ${pkg}_tool.new ${rawsite}/${pkg}_tool
-      chmod 755 ${pkg}_tool.new
-      if cmp -s ${pkg}_tool ${pkg}_tool.new ; then
-         rm ${pkg}_tool.new
-         echo "not needed."
-      else
-         echo "this file was updated.  Please run this command again,"
-         echo " then rebuild everything."
-         mv ${pkg}_tool.new ${pkg}_tool
-         trap - EXIT
-         exit 0
-      fi
-   fi
+(
+cat <<'EOF'
+#
+# This file is sourced after lorax_tool configure_pkg does initializations,
+# including picking up non-default values from the build configuration for
+# root_dir, var_dir, tmp_dir, and log_dir.
+#
+# The customizations below are the main ones needed to configure a
+# server at non-default locations.  Uncomment and edit as needed.
+# Values shown are not defaults, but rather example values.
+#
+#${root}/bin/lorax_env lorax config secret_key mypasswd
+#${root}/bin/lorax_env lorax config user www
+#${root}/bin/lorax_env lorax config group www
+#${root}/bin/lorax_env lorax config data /usr/local/www/data/lorax/${version}
+#${root}/bin/lorax_env lorax config userdata /persist/lorax/${version}
+#${root}/bin/lorax_env lorax config host 127.0.0.1
+#${root}/bin/lorax_env lorax config nginx_server_name mywebsite.org
+#${root}/bin/lorax_env lorax config port 58927
+#${root}/bin/lorax_env lorax config sentry_dsn https://MYDSN@sentry.io/lorax
+#${root}/bin/lorax_env lorax config crashmail_email user@example.com
+EOF
+) > config_example.sh.new
    # Check for updates to other files, in an edit-aware way.
-   curl -L -s -o build_example.sh.new ${rawsite}/build_example.sh
-   curl -L -s -o config_example.sh.new ${rawsite}/config_example.sh
    for f in build_example.sh config_example.sh; do
       if [ -e ${f} ]; then
          if cmp -s ${f} ${f}.new; then
             rm ${f}.new # no change
          else
            updates=1
-           echo "$f has been updated."
+           echo "$f has been updated." >&1
            mv ${f} ${f}.old
            chmod 755 ${f}.new
            mv ${f}.new ${f}
@@ -378,9 +432,7 @@ Options:
          chmod 755 ${f}.new
          mv ${f}.new ${f}
       fi
-   done
-   # If my_ files have changed versus example, warn but don't replace.
-   for f in build_example.sh config_example.sh ; do
+   # If my_ files have changed versus example, warn but do not replace.
      my_f="my_${f/_example/}"
      if [ -e ${f}.old ]; then
         cmp_f="${f}.old" # look for changes against old file
@@ -396,13 +448,13 @@ Options:
        else
           if [ -e ${f}.old ]; then
             mv ${f}.old ${f}.save
-            echo "Example file on which your edited ${my_f} was based has changed."
-            echo "Review the following differences between ${f} and ${f}.save"
-            echo "and apply them, if necessary to ${my_f}:"
+            echo "Example file on which your edited ${my_f} was based has changed." >&1
+            echo "Review the following differences between ${f} and ${f}.save" >&1
+            echo "and apply them, if necessary to ${my_f}:" >&1
             set +e
             diff -u ${f}.save ${f}
           else
-            echo "${my_f} differs from the (unchanged) example file."
+            echo "${my_f} differs from the (unchanged) example file." >&1
           fi
        fi
        else
@@ -410,19 +462,6 @@ Options:
      fi
    done
    rm -f $build_example.sh.old config_example.sh.old
-   pypi=`pypi`
-   version=`version`
-   if [ "version" == "${pkg} build not configured" ]; then
-      echo "Next run \"./${script_name} build\" to build and configure ${pkg}."
-   elif [ "$updates" -eq 1 ]; then
-      echo "Update build/configuration files found, please re-build using"
-      echo "    ./${script_name} build"
-   elif [ "$pypi" == "$version" ]; then
-      echo "The latest version of ${pkg} (${pypi}) is installed, no need for updates."
-   else
-      echo "You can update from installed version (${version}) to latest (${pypi}) with"
-      echo "   ./${script_name} pip_install"
-   fi
 }
 init() {
    #
@@ -439,7 +478,7 @@ init() {
    set_value redis 4.0.1
    set_value nginx 1.13.4
    if [[ "$platform" == "Linux" ]]; then
-      echo "Platform is linux."
+      echo "Platform is linux." >&1
       set_value bin_dir ~/bin
       set_value platform linux
       set_value make make
@@ -448,7 +487,7 @@ init() {
       set_value raxml_model .SSE3.PTHREADS.gcc
       set_value raxml_binsuffix -PTHREADS-SSE3
    elif [[ "$platform" == *"BSD" ]]; then
-      echo "Platform is bsd."
+      echo "Platform is bsd." >&1
       set_value platform bsd
       set_value bin_dir ~/bin
       set_value make gmake
@@ -457,7 +496,7 @@ init() {
       set_value raxml_binsuffix -PTHREADS-SSE3
       set_value redis_cflags -DAF_LOCAL=AF_UNIX
    elif [[ "$platform" == "Darwin" ]]; then
-      echo "Platform is mac.  You must have XCODE installed."
+      echo "Platform is mac.  You must have XCODE installed." >&1
       set_value platform mac
       set_value bin_dir /usr/local/bin
       set_value make make
@@ -466,7 +505,7 @@ init() {
       set_value raxml_binsuffix -PTHREADS-SSE3
       set_value redis_cflags ""
    else
-      echo "WARNING--Unknown platform ${platform}, pretending it is linux."
+      echo "WARNING--Unknown platform ${platform}, pretending it is linux." >&2
       set_value platform linux
       set_value bin_dir ~/bin
       set_value make make
@@ -497,7 +536,7 @@ Packages:
       for package in $commandlist; do
          version=`get_value $package`
          if [ "$version" == "system" ]; then
-           echo "System version of $package will be used, skipping build."
+           echo "System version of $package will be used, skipping build." >&2
          else
            install_$package ${version} ${root} ${cc} ${make}
          fi
@@ -521,10 +560,10 @@ link_env() {
    #
    root=`get_value root_dir`
    bin_dir=`get_value bin_dir`
-   echo "linking ${pkg}_env to ${bin_dir}"
+   echo "linking ${pkg}_env to ${bin_dir}" >&1
    if [ ! -e ${bin_dir} ]; then
-     echo "Creating binary directory at ${bin_dir}"
-     echo "Make sure it is on your PATH."
+     echo "Creating binary directory at ${bin_dir}" >&1
+     echo "Make sure it is on your PATH." >&1
      mkdir ${bin_dir}
    elif [ -h ${bin_dir}/${pkg}_env ]; then
      rm -f ${bin_dir}/${pkg}_env
@@ -539,7 +578,7 @@ make_dirs() {
    var=`get_value var_dir`
    tmp=`get_value tmp_dir`
    log=`get_value log_dir`
-   echo "Creating directories in ${root}."
+   echo "Creating directories in ${root}." >&1
    mkdir -p ${root}/{bin,configuration}
    cp -R ${confdir}/ ${root}/configuration
    mkdir -p ${root}/etc/nginx
@@ -553,11 +592,11 @@ link_python() {
    python_version=`get_value python`
    cd $root_bin
    if [ ! -e python ]; then
-      echo "creating python ${python_version} link in ${root_bin}."
+      echo "creating python ${python_version} link in ${root_bin}." >&1
       ln -s python${python_version%.*} python
    fi
    if [ ! -e pip_install ]; then
-      echo "creating pip link in ${root_bin}."
+      echo "creating pip link in ${root_bin}." >&1
       ln -s pip${python_version%%.*} pip
    fi
 }
@@ -576,7 +615,7 @@ pip_install() {
    pkg_env_path="${root}/bin/${pkg}_env"
    pkg_version="`${pkg_env_path} ${pkg} config version`"
    set_value version $pkg_version
-   echo "${pkg} version $pkg_version is now installed."
+   echo "${pkg} version $pkg_version is now installed." >&1
 }
 pypi() {
   #
@@ -612,7 +651,7 @@ shell() {
    set +e
    old_prompt="$PS1"
    pushd $root 2&>/dev/null
-   echo "Executing commands in ${root} with ${root}/bin in path, control-D to exit."
+   echo "Executing commands in ${root} with ${root}/bin in path, control-D to exit." >&1
    export PS1="${script_name}> "
    bash
    popd 2&>/dev/null
@@ -626,7 +665,7 @@ Interrupt this script if you do not wish to test at this time.
 """
    set +e
    if [ "$1" != "-y" ]; then
-      echo "$TEST_DOC"
+      echo "$TEST_DOC" >&1
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -636,7 +675,7 @@ Interrupt this script if you do not wish to test at this time.
    fi
    set -e
    root="`get_value root_dir`"
-   echo "Running lorax processes."
+   echo "Running lorax processes." >&1
    ${root}/bin/lorax_env supervisord
    # Wait until nothing is STARTING.
    while ${root}/bin/lorax_env supervisorctl status | grep STARTING >/dev/null; do sleep 5; done
@@ -645,18 +684,52 @@ Interrupt this script if you do not wish to test at this time.
    # Create the test directory and cd to it.
    mkdir -p ${test_dir}
    pushd ${test_dir}
-   echo "Getting a set of test files in the ${test_dir} directory."
+   echo "Getting a set of test files in the ${test_dir} directory." >&1
    ${root}/bin/lorax_env lorax create_test_files --force
-   echo "Running test of lorax server."
+   echo "Running test of lorax server." >&1
    ./test_targets.sh
-   echo ""
+   echo "" >&1
    popd
    # Clean up.  Note that lorax process doesn't stop properly from
    # shutdown alone across all platforms.
-   echo "Stopping lorax processes."
+   echo "Stopping lorax processes." >&1
    ${root}/bin/lorax_env supervisorctl stop lorax alignment treebuilding nginx
    ${root}/bin/lorax_env supervisorctl shutdown
-   echo "Tests completed successfully."
+   echo "Tests completed successfully." >&1
+}
+update() {
+   #
+   # Updates self.
+   #
+   rawsite="https://raw.githubusercontent.com/LegumeFederation/${pkg}/master/build_scripts"
+   updated=0
+   printf "Checking for self-update..."
+   curl -L -s -o ${pkg}_tool.new ${rawsite}/${pkg}_tool
+   chmod 755 ${pkg}_tool.new
+   if cmp -s ${pkg}_tool ${pkg}_tool.new ; then
+      rm ${pkg}_tool.new
+      echo "not needed." >&1
+   else
+      updated=1
+      mv ${pkg}_tool.new ${pkg}_tool
+   fi
+   pypi=`pypi`
+   version=`version`
+   if [ "version" == "${pkg} build not configured" ]; then
+      echo "Next run \"./${script_name} build\" to build and configure ${pkg}." >&1
+   elif [ "$updated" -eq 1 ]; then
+      echo "This script was updated. Please re-build ${pkg} using" >&1
+      if [ -e my_build.sh] ; then
+         echo "   ./${script_name} create_scripts" >&1
+         echo "and" >&1
+      fi
+      echo "    ./${script_name} build" >&1
+   elif [ "$pypi" == "$version" ]; then
+      echo "The latest version of ${pkg} (${pypi}) is installed, no need for updates." >&1
+   else
+      echo "You can update from installed version (${version}) to latest (${pypi}) with" >&1
+      echo "   ./${script_name} pip_install" >&1
+   fi
 }
 version() {
   #
@@ -698,8 +771,8 @@ case $command in
 "configure_pkg")
   configure_pkg $@
   ;;
-"download")
-  download $@
+"create_scripts")
+  create_scripts $@
   ;;
 "init")
    init $@
@@ -728,6 +801,9 @@ case $command in
 "testify")
    testify $@
    ;;
+"update")
+  update $@
+  ;;
 "version")
    version $@
    ;;
