start command in _env

diff --git a/build_scripts/lorax_tool b/build_scripts/lorax_tool
--- a/build_scripts/lorax_tool
+++ b/build_scripts/lorax_tool
@@ -21,10 +21,10 @@ fi
 version="0.94"
 platform="`uname`"
 error_exit() {
-   echo "ERROR--unexpected exit from ${BASH_SOURCE} script at line:"
-   echo "   $BASH_COMMAND"
-   echo "Build directory is \"${build_dir}\"."
-   echo "Test directory is \"${test_dir}\"."
+   >&2 echo "ERROR--unexpected exit from ${BASH_SOURCE} script at line:"
+   >&2 echo "   $BASH_COMMAND"
+   >&2 echo "Build directory is \"${build_dir}\"."
+   >&2 echo "Test directory is \"${test_dir}\"."
 }
 trap error_exit EXIT
 TOP_DOC="""Builds and installs ${pkg} components.
@@ -101,7 +101,7 @@ get_value() {
 # Installation functions.
 #
 install_python() {
-   echo "Installing Python $1 to ${2}."
+   >&1 echo "Installing Python $1 to ${2}."
    curl -L -o Python-${1}.tar.gz  https://www.python.org/ftp/python/${1}/Python-${1}.tar.xz
    tar xf Python-${1}.tar.gz
    rm Python-${1}.tar.gz
@@ -114,7 +114,7 @@ install_python() {
 install_raxml() {
    model="`get_value raxml_model`"
    binsuffix="`get_value raxml_binsuffix`"
-   echo "Installing RAxML version $1 to $2 using ${model} model."
+   >&1 echo "Installing RAxML version $1 to $2 using ${model} model."
    curl -L -o raxml_v${1}.tar.gz https://github.com/stamatak/standard-RAxML/archive/v${1}.tar.gz
    tar xf raxml_v${1}.tar.gz 
    rm raxml_v${1}.tar.gz 
@@ -125,7 +125,7 @@ install_raxml() {
    rm -r standard-RAxML-${1}
 }
 install_hmmer() {
-   echo "Installing HMMer $1 to ${2}."
+   >&1 echo "Installing HMMer $1 to ${2}."
    curl -L -o hmmer-${1}-linux-intel-x86_64.tar.gz http://eddylab.org/software/hmmer3/${1}/hmmer-${1}-linux-intel-x86_64.tar.gz
    tar xf hmmer-${1}-linux-intel-x86_64.tar.gz 
    rm hmmer-${1}-linux-intel-x86_64.tar.gz 
@@ -138,7 +138,7 @@ install_hmmer() {
 }
 install_redis() {
    redis_cflags="`get_value redis_cflags`" # -DAF_LOCAL=1
-   echo "Installing redis $1 to ${2}."
+   >&1 echo "Installing redis $1 to ${2}."
    curl -L -o redis-${1}.tar.gz  http://download.redis.io/releases/redis-${1}.tar.gz
    tar xf redis-${1}.tar.gz
    rm redis-${1}.tar.gz
@@ -157,7 +157,7 @@ install_nginx() {
    var="`get_value var_dir`"
    tmp="`get_value tmp_dir`"
    log="`get_value log_dir`"
-   echo "Installing nginx $1 to ${2}."
+   >&1 echo "Installing nginx $1 to ${2}."
    curl -L -o nginx-${1}.tar.gz http://nginx.org/download/nginx-${1}.tar.gz
    tar xf nginx-${1}.tar.gz
    rm nginx-${1}.tar.gz
@@ -206,7 +206,7 @@ You should stop and edit my_build.sh if you wish to:
 You may run this command with a \"-y\" argument to skip this question.
 """
    if [ "$1" != "-y" ]; then
-      echo "$BUILD_DOC"
+      >&1 echo "$BUILD_DOC"
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -218,15 +218,15 @@ You may run this command with a \"-y\" argument to skip this question.
    # Configure the build.
    init
    if [ -e my_build.sh ]; then
-      echo "Sourcing build specifics in my_build.sh."
+      >&1 echo "Sourcing build specifics in my_build.sh."
       source my_build.sh
    else
-      echo "WARNING--my_build.sh not found, using defaults."
+      >&2 echo "WARNING--my_build.sh not found, using defaults."
    fi
    set_value all
    make_dirs
    # Build the binaries.
-   echo "Doing C/C++ binary installs."
+   >&1 echo "Doing C/C++ binary installs."
    install
    # The following exports are needed for the freshly-built python to run
    # on BSD (and probably harmless on others).
@@ -237,17 +237,17 @@ You may run this command with a \"-y\" argument to skip this question.
       export LANG=en_US.UTF-8
    fi
    # Do pip installs.
-   echo "Doing python installs."
+   >&1 echo "Doing python installs."
    link_python    # python and pip links
    pip_install    # Do installs for lorax and dependencies
    link_env       # put lorax_env in PATH
    # Test to make sure it runs.
-   echo "Testing lorax binary."
+   >&1 echo "Testing lorax binary."
    root="`get_value root_dir`"
    version > ${root}/version
-   echo "Installation was successful."
-   echo "You should now proceed with configuring lorax via the command"
-   echo "   lorax_tool configure_pkg"
+   >&1 echo "Installation was successful."
+   >&1 echo "You should now proceed with configuring lorax via the command"
+   >&1 echo "   lorax_tool configure_pkg"
 }
 config() {
   CONFIG_DOC="""Sets/displays key/value pairs for the $pkg build system.
@@ -266,10 +266,10 @@ Arguments:
       exit 1
     elif [ "$#" -eq 1 ]; then # get
       if [ "$1" == "all" ]; then
-        echo "Build configuration values for ${pkg}." >&1
-        echo "These values are stored in ${confdir}." >&1
-        echo -e "       key         \t       value" >&1
-        echo -e "-------------------\t------------------" >&1
+        >&1 echo "Build configuration values for ${pkg}."
+        >&1 echo "These values are stored in ${confdir}."
+        >&1 echo -e "       key         \t       value"
+        >&1 echo -e "-------------------\t------------------"
         for key in `ls ${confdir}`; do
           value="`get_value ${key}`"
         printf '%-20s\t%s\n' ${key} ${value} >&1
@@ -301,7 +301,7 @@ You should stop and edit my_config.sh if you wish to:
 You may run this command with a \"-y\" argument to skip this question.
 """
    if [ "$1" != "-y" ]; then
-      echo "$CONFIGURE_DOC" >&1
+      >&1 echo "$CONFIGURE_DOC"
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -316,36 +316,36 @@ You may run this command with a \"-y\" argument to skip this question.
    log_dir="`get_value log_dir`"
    tmp_dir="`get_value tmp_dir`"
    if [ "$var_dir" != "${root}/var" ]; then
-      echo "Configuring non-default var directory ${var_dir}." >&1
+      >&1 echo "Configuring non-default var directory ${var_dir}."
       ${root}/bin/lorax_env lorax config var $var_dir
    fi
    if [ "$log_dir" != "${var_dir}/log" ]; then
-      echo "Configuring non-default log directory ${log_dir}." >&1
+      >&1 echo "Configuring non-default log directory ${log_dir}."
       ${root}/bin/lorax_env lorax config log $log_dir
    fi
    if [ "$tmp_dir" != "${var_dir}/tmp" ]; then
-      echo "Configuring non-default tmp directory ${tmp_dir}." >&1
+      >&1 echo "Configuring non-default tmp directory ${tmp_dir}."
       ${root}/bin/lorax_env lorax config tmp $tmp_dir
    fi
    if [ -e my_config.sh ]; then
-      echo "Sourcing configuration specifics in my_config.sh."
+      >&1 echo "Sourcing configuration specifics in my_config.sh."
       source my_config.sh
    else
-      echo "WARNING--my_config.sh not found, using defaults."
+      >&2 echo "WARNING--my_config.sh not found, using defaults."
    fi
    # Save a copy of the configuration to a time-stamped file.
    config_filename="lorax_config-`date '+%Y-%m-%d-%H-%M'`.txt"
    ${root}/bin/lorax_env lorax config > ${confdir}/${config_filename}
    # Create the configured instance.
-   echo "Creating a configured instance at ${root}." >&1
+   >&1 echo "Creating a configured instance at ${root}."
    ${root}/bin/lorax_env lorax create_instance --force
    # Set the password for restricted parts of the site.
    passwd="`${root}/bin/lorax_env lorax config secret_key`"
-   echo "Setting the http password to \"${passwd}\";" >&1
-   echo "please write it down, because you will need it to access some services." >&1
+   >&1 echo "Setting the http password to \"${passwd}\";"
+   >&1 echo "please write it down, because you will need it to access some services."
    ${root}/bin/lorax_env lorax set_htpasswd --force
-   echo "To run the test suite, issue the command:" >&1
-   echo "   ./${script_name} testify" >&1
+   >&1 echo "To run the test suite, issue the command:"
+   >&1 echo "   ./${script_name} testify"
 }
 create_scripts() {
 (
@@ -424,7 +424,7 @@ EOF
             rm ${f}.new # no change
          else
            updates=1
-           echo "$f has been updated." >&1
+           >&1 echo "$f has been updated."
            mv ${f} ${f}.old
            chmod 755 ${f}.new
            mv ${f}.new ${f}
@@ -450,13 +450,13 @@ EOF
        else
           if [ -e ${f}.old ]; then
             mv ${f}.old ${f}.save
-            echo "Example file on which your edited ${my_f} was based has changed." >&1
-            echo "Review the following differences between ${f} and ${f}.save" >&1
-            echo "and apply them, if necessary to ${my_f}:" >&1
+            >&1 echo "Example file on which your edited ${my_f} was based has changed."
+            >&1 echo "Review the following differences between ${f} and ${f}.save"
+            >&1 echo "and apply them, if necessary to ${my_f}:"
             set +e
             diff -u ${f}.save ${f}
           else
-            echo "${my_f} differs from the (unchanged) example file." >&1
+            >&1 echo "${my_f} differs from the (unchanged) example file."
           fi
        fi
        else
@@ -480,7 +480,7 @@ init() {
    set_value redis 4.0.1
    set_value nginx 1.13.5
    if [[ "$platform" == "Linux" ]]; then
-      echo "Platform is linux." >&1
+      >&1 echo "Platform is linux."
       set_value bin_dir ~/bin
       set_value platform linux
       set_value make make
@@ -489,7 +489,7 @@ init() {
       set_value raxml_model .SSE3.PTHREADS.gcc
       set_value raxml_binsuffix -PTHREADS-SSE3
    elif [[ "$platform" == *"BSD" ]]; then
-      echo "Platform is bsd." >&1
+      >&1 echo "Platform is bsd."
       set_value platform bsd
       set_value bin_dir ~/bin
       set_value make gmake
@@ -498,7 +498,7 @@ init() {
       set_value raxml_binsuffix -PTHREADS-SSE3
       set_value redis_cflags -DAF_LOCAL=AF_UNIX
    elif [[ "$platform" == "Darwin" ]]; then
-      echo "Platform is mac.  You must have XCODE installed." >&1
+      >&2 echo "Platform is mac.  Warning: You must have XCODE installed."
       set_value platform mac
       set_value bin_dir /usr/local/bin
       set_value make make
@@ -507,7 +507,7 @@ init() {
       set_value raxml_binsuffix -PTHREADS-SSE3
       set_value redis_cflags ""
    else
-      echo "WARNING--Unknown platform ${platform}, pretending it is linux." >&2
+      >&2 echo "WARNING--Unknown platform ${platform}, pretending it is linux."
       set_value platform linux
       set_value bin_dir ~/bin
       set_value make make
@@ -538,7 +538,7 @@ Packages:
       for package in $commandlist; do
          version="`get_value $package`"
          if [ "$version" == "system" ]; then
-           echo "System version of $package will be used, skipping build." >&2
+           >&1 echo "System version of $package will be used, skipping build."
          else
            install_$package ${version} ${root} ${cc} ${make}
          fi
@@ -562,10 +562,10 @@ link_env() {
    #
    root="`get_value root_dir`"
    bin_dir="`get_value bin_dir`"
-   echo "linking ${pkg}_env to ${bin_dir}" >&1
+   >&1 echo "linking ${pkg}_env to ${bin_dir}"
    if [ ! -e ${bin_dir} ]; then
-     echo "Creating binary directory at ${bin_dir}" >&1
-     echo "Make sure it is on your PATH." >&1
+     >&1 echo "Creating binary directory at ${bin_dir}"
+     >&1 echo "Make sure it is on your PATH."
      mkdir ${bin_dir}
    elif [ -h ${bin_dir}/${pkg}_env ]; then
      rm -f ${bin_dir}/${pkg}_env
@@ -584,10 +584,10 @@ make_dirs() {
             "`get_value log_dir`/nginx")
    for dir in "${dirlist[@]}" ; do
       if [ ! -e "$dir" ]; then
-         echo "making directory $dir"
+         >&1 echo "making directory $dir"
          mkdir -p $dir
       else
-         echo "directory $dir already exists"
+         >&1 echo "directory $dir already exists"
       fi
    done
 }
@@ -597,11 +597,11 @@ link_python() {
    python_version="`get_value python`"
    cd $root_bin
    if [ ! -e python ]; then
-      echo "creating python ${python_version} link in ${root_bin}." >&1
+      >&1 echo "creating python ${python_version} link in ${root_bin}."
       ln -s python${python_version%.*} python
    fi
    if [ ! -e pip_install ]; then
-      echo "creating pip link in ${root_bin}." >&1
+      >&1 echo "creating pip link in ${root_bin}."
       ln -s pip${python_version%%.*} pip
    fi
 }
@@ -620,7 +620,7 @@ pip_install() {
    pkg_env_path="${root}/bin/${pkg}_env"
    pkg_version="`${pkg_env_path} ${pkg} config version`"
    set_value version $pkg_version
-   echo "${pkg} version $pkg_version is now installed." >&1
+   >&1 echo "${pkg} version $pkg_version is now installed."
 }
 pip_upgrade() {
    #
@@ -637,7 +637,7 @@ pip_upgrade() {
    pkg_env_path="${root}/bin/${pkg}_env"
    pkg_version="`${pkg_env_path} ${pkg} config version`"
    set_value version $pkg_version
-   echo "${pkg} version $pkg_version is now installed." >&1
+   >&1 echo "${pkg} version $pkg_version is now installed."
 }
 pypi() {
   #
@@ -673,7 +673,7 @@ shell() {
    set +e
    old_prompt="$PS1"
    pushd $root 2&>/dev/null
-   echo "Executing commands in ${root} with ${root}/bin in path, control-D to exit." >&1
+   >&1 echo "Executing commands in ${root} with ${root}/bin in path, control-D to exit."
    export PS1="${script_name}> "
    bash
    popd 2&>/dev/null
@@ -687,7 +687,7 @@ Interrupt this script if you do not wish to test at this time.
 """
    set +e
    if [ "$1" != "-y" ]; then
-      echo "$TEST_DOC" >&1
+      >&1 echo "$TEST_DOC"
       read -p "Do you want to continue? <(y)> " response
       if [ ! -z "$response" ]; then
          if [ "$response" != "y" ]; then
@@ -697,7 +697,7 @@ Interrupt this script if you do not wish to test at this time.
    fi
    set -e
    root="`get_value root_dir`"
-   echo "Running lorax processes." >&1
+   >&1 echo "Running lorax processes."
    ${root}/bin/lorax_env supervisord
    # Wait until nothing is STARTING.
    while ${root}/bin/lorax_env supervisorctl status | grep STARTING >/dev/null; do sleep 5; done
@@ -706,18 +706,18 @@ Interrupt this script if you do not wish to test at this time.
    # Create the test directory and cd to it.
    mkdir -p ${test_dir}
    pushd ${test_dir}
-   echo "Getting a set of test files in the ${test_dir} directory." >&1
+   >&1 echo "Getting a set of test files in the ${test_dir} directory."
    ${root}/bin/lorax_env lorax create_test_files --force
-   echo "Running test of lorax server." >&1
+   >&1 echo "Running test of lorax server."
    ./test_targets.sh
-   echo "" >&1
+   >&1 echo ""
    popd
    # Clean up.  Note that lorax process doesn't stop properly from
    # shutdown alone across all platforms.
-   echo "Stopping lorax processes." >&1
+   >&1 echo "Stopping lorax processes."
    ${root}/bin/lorax_env supervisorctl stop lorax alignment treebuilding nginx
    ${root}/bin/lorax_env supervisorctl shutdown
-   echo "Tests completed successfully." >&1
+   >&1 echo "Tests completed successfully."
 }
 update() {
    #
@@ -729,25 +729,25 @@ update() {
    chmod 755 ${pkg}_tool.new
    if cmp -s ${pkg}_tool ${pkg}_tool.new ; then
       rm ${pkg}_tool.new
-      echo "not needed." >&1
+      >&1 echo "not needed." >&1
    else
       mv ${pkg}_tool.new ${pkg}_tool
-            echo "This script was updated. Please re-build ${pkg} using" >&1
+            >&2 echo "This script was updated. Please re-build ${pkg} using"
       if [ -e my_build.sh ] ; then
-         echo "   ./${script_name} create_scripts" >&1
-         echo "and" >&1
+         >&2 echo "   ./${script_name} create_scripts"
+         >&2 echo "and"
       fi
-      echo "    ./${script_name} build" >&1
+      >&2 echo "    ./${script_name} build"
    fi
    pypi="`pypi`"
    version="`version`"
    if [ "${version}" == "${pkg} build not configured" ]; then
-      echo "Next run \"./${script_name} build\" to build and configure ${pkg}." >&1
+      >&1 echo "Next run \"./${script_name} build\" to build and configure ${pkg}."
    elif [ "$pypi" == "$version" ]; then
-      echo "The latest version of ${pkg} (${pypi}) is installed, no need for updates." >&1
+      >&1 echo "The latest version of ${pkg} (${pypi}) is installed, no need for updates."
    else
-      echo "You can update from installed version (${version}) to latest (${pypi}) with" >&1
-      echo "   ./${script_name} pip_install" >&1
+      >&1 echo "You can update from installed version (${version}) to latest (${pypi}) with"
+      >&1 echo "   ./${script_name} pip_install"
    fi
 }
 version() {
